import { Repository } from './../models/portfolio.models';

export const createTestRepository = (id = 978832136): Repository => ({
  id,
  node_id: 'R_kgDOOlfLCA',
  name: `Repository id: ${id}`,
  full_name: 'srednicki-lukasz/srednicki-lukasz.github.io',
  private: false,
  owner: {
    login: 'srednicki-lukasz',
    id: 54948608,
    node_id: 'MDQ6VXNlcjU0OTQ4NjA4',
    avatar_url: 'https://avatars.githubusercontent.com/u/54948608?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/srednicki-lukasz',
    html_url: 'https://github.com/srednicki-lukasz',
    followers_url: 'https://api.github.com/users/srednicki-lukasz/followers',
    following_url: 'https://api.github.com/users/srednicki-lukasz/following{/other_user}',
    gists_url: 'https://api.github.com/users/srednicki-lukasz/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/srednicki-lukasz/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/srednicki-lukasz/subscriptions',
    organizations_url: 'https://api.github.com/users/srednicki-lukasz/orgs',
    repos_url: 'https://api.github.com/users/srednicki-lukasz/repos',
    events_url: 'https://api.github.com/users/srednicki-lukasz/events{/privacy}',
    received_events_url: 'https://api.github.com/users/srednicki-lukasz/received_events',
    type: 'User',
    user_view_type: 'public',
    site_admin: false,
  },
  html_url: 'https://github.com/srednicki-lukasz/srednicki-lukasz.github.io',
  description: 'Portfolio App.',
  fork: false,
  url: 'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io',
  forks_url: 'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io/forks',
  keys_url: 'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io/keys{/key_id}',
  collaborators_url:
    'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io/collaborators{/collaborator}',
  teams_url: 'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io/teams',
  hooks_url: 'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io/hooks',
  issue_events_url: 'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io/issues/events{/number}',
  events_url: 'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io/events',
  assignees_url: 'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io/assignees{/user}',
  branches_url: 'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io/branches{/branch}',
  tags_url: 'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io/tags',
  blobs_url: 'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io/git/blobs{/sha}',
  git_tags_url: 'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io/git/tags{/sha}',
  git_refs_url: 'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io/git/refs{/sha}',
  trees_url: 'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io/git/trees{/sha}',
  statuses_url: 'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io/statuses/{sha}',
  languages_url: 'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io/languages',
  stargazers_url: 'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io/stargazers',
  contributors_url: 'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io/contributors',
  subscribers_url: 'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io/subscribers',
  subscription_url: 'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io/subscription',
  commits_url: 'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io/commits{/sha}',
  git_commits_url: 'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io/git/commits{/sha}',
  comments_url: 'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io/comments{/number}',
  issue_comment_url:
    'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io/issues/comments{/number}',
  contents_url: 'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io/contents/{+path}',
  compare_url: 'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io/compare/{base}...{head}',
  merges_url: 'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io/merges',
  archive_url: 'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io/{archive_format}{/ref}',
  downloads_url: 'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io/downloads',
  issues_url: 'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io/issues{/number}',
  pulls_url: 'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io/pulls{/number}',
  milestones_url: 'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io/milestones{/number}',
  notifications_url:
    'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io/notifications{?since,all,participating}',
  labels_url: 'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io/labels{/name}',
  releases_url: 'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io/releases{/id}',
  deployments_url: 'https://api.github.com/repos/srednicki-lukasz/srednicki-lukasz.github.io/deployments',
  created_at: '2025-05-06T15:17:08Z',
  updated_at: '2025-05-06T15:17:12Z',
  pushed_at: '2025-05-06T15:17:09Z',
  git_url: 'git://github.com/srednicki-lukasz/srednicki-lukasz.github.io.git',
  ssh_url: 'git@github.com:srednicki-lukasz/srednicki-lukasz.github.io.git',
  clone_url: 'https://github.com/srednicki-lukasz/srednicki-lukasz.github.io.git',
  svn_url: 'https://github.com/srednicki-lukasz/srednicki-lukasz.github.io',
  homepage: null,
  size: 0,
  stargazers_count: 0,
  watchers_count: 0,
  language: null,
  has_issues: true,
  has_projects: true,
  has_downloads: true,
  has_wiki: true,
  has_pages: true,
  has_discussions: false,
  forks_count: 0,
  mirror_url: null,
  archived: false,
  disabled: false,
  open_issues_count: 0,
  license: null,
  allow_forking: true,
  is_template: false,
  web_commit_signoff_required: false,
  topics: [],
  visibility: 'public',
  forks: 0,
  open_issues: 0,
  watchers: 0,
  default_branch: 'main',
});

export const createTestRepositories = (count = 1): Repository[] => {
  return Array(count).fill(createTestRepository());
};
